steps:
  # Step 1: Basic install check (keeps pipeline multi-step)
  - name: "python:3.11"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd app
        pip install -r requirements.txt

  # Step 2: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd app
        gcloud app deploy app.yaml --quiet

timeout: "1200s"
